### ISSUE TITLE
About your pretrained_resnet18.ckpt

### ISSUE THREAD

**Issue by myt889** [Sunner4nwpu/RA-UWML-AU-Pytorch#1]
Hi, thanks for your nice work and code, can you share your pretrained models: pretrained_resnet18.ckpt? thank you very much.

Best regards!

**Comment by myt889** [comment]
I mean the backbone Es of the RoI-Net  that pre-trained on the face recognition  database.  Thank you very much.

**Comment by Sunner4nwpu** [comment]
hi, the pretrained resnet18 is shared, see /codes/README.md

**Comment by myt889** [comment]
> hi, the pretrained resnet18 is shared, see /codes/README.md

ok，thank you very much!
